version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8001"
    env_file:
      - backend/.env
    environment:
      - PYTHONPATH=/app
      - SECRETS_PATH=/app/backend/secrets.json
    volumes:
      - ./uploads:/app/uploads
      - ./backend/secrets.json:/app/backend/secrets.json
    depends_on:
      - postgres

  # 2) Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app       # optional for dev hot-reload
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: layernexus-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html  
    depends_on:
      - backend
      - frontend

  # 3) Postgres for persistence
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: layernexus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
